### ISSUE TITLE
THIS LIBRARY CONTAINS BILLING DEPENDICIES!!!!!

### ISSUE THREAD

**Issue by SoftwareAdvise** [WindSekirun/SectionCalendarView#5]
AND THIS DONT LET ME ADD DEPENDENCIES TO BILLING MYSELF..

HORRIBLE

**Comment by WindSekirun** [comment]
You can use ServiceConnection yourself to bind Billing Services. There's no reason to angry.

Or, you can exclude com.android.billing group using gradle.

And, All-caped title and message makes me feel so bad. I'M NOT YOUR PROPERTY So speak kindly and describe your problem and attach some log to inspect.

**Comment by SoftwareAdvise** [comment]
excuse me.. i felt in panic and angry.. excuse me again..
i've solved pasting your library in my project without using dependencies
